-- ============================================================
--  Emissor NFS-e Maradel — Migration 0001 (schema + RLS + storage)
--  Rode este arquivo inteiro no SQL Editor do Supabase.
--  Idempotente onde possível (IF NOT EXISTS / on conflict).
-- ============================================================

-- pgcrypto fornece gen_random_uuid()
create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- ENUMS
-- ------------------------------------------------------------
do $$ begin
  create type user_role          as enum ('cliente','analista');
exception when duplicate_object then null; end $$;

do $$ begin
  create type regime_tributario  as enum ('SP','Nacional');
exception when duplicate_object then null; end $$;

do $$ begin
  create type tomador_tipo       as enum ('PJ','PF');
exception when duplicate_object then null; end $$;

do $$ begin
  create type solicitacao_status as enum ('solicitada','em_emissao','emitida','cancelada');
exception when duplicate_object then null; end $$;

-- ------------------------------------------------------------
-- TABELA: profiles  (papel do usuário, ligado ao auth.users)
-- ------------------------------------------------------------
create table if not exists public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  role       user_role   not null default 'cliente',
  nome       text,
  email      text,
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- TABELA: clientes  (prestador de serviço — dono dos dados)
-- ------------------------------------------------------------
create table if not exists public.clientes (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users(id) on delete cascade,
  razao_social text not null,
  cnpj         text not null,
  regime       regime_tributario not null default 'SP',
  created_at   timestamptz not null default now()
);
create index if not exists idx_clientes_user on public.clientes(user_id);

-- ------------------------------------------------------------
-- TABELA: tomadores  (cadastro reutilizável por cliente)
-- ------------------------------------------------------------
create table if not exists public.tomadores (
  id         uuid primary key default gen_random_uuid(),
  cliente_id uuid not null references public.clientes(id) on delete cascade,
  tipo       tomador_tipo not null,
  doc        text not null,            -- CNPJ ou CPF (somente dígitos ou formatado)
  nome       text not null,            -- razão social (PJ) ou nome (PF)
  endereco   text,
  cidade     text,
  uf         text,
  cep        text,
  created_at timestamptz not null default now()
);
create index if not exists idx_tomadores_cliente on public.tomadores(cliente_id);

-- ------------------------------------------------------------
-- TABELA: solicitacoes
-- ------------------------------------------------------------
create table if not exists public.solicitacoes (
  id          uuid primary key default gen_random_uuid(),
  cliente_id  uuid not null references public.clientes(id) on delete cascade,
  tomador_id  uuid not null references public.tomadores(id) on delete restrict,
  descricao   text not null,
  valor       numeric(12,2) not null check (valor >= 0),
  competencia text not null,           -- formato 'YYYY-MM'
  status      solicitacao_status not null default 'solicitada',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists idx_solic_cliente on public.solicitacoes(cliente_id);
create index if not exists idx_solic_status  on public.solicitacoes(status);

-- ------------------------------------------------------------
-- TABELA: notas  (uma nota por solicitação emitida)
-- ------------------------------------------------------------
create table if not exists public.notas (
  id             uuid primary key default gen_random_uuid(),
  solicitacao_id uuid not null references public.solicitacoes(id) on delete cascade,
  numero         text,
  data_emissao   date,
  pdf_url        text,                 -- caminho do arquivo no bucket 'notas'
  xml_url        text,
  created_at     timestamptz not null default now()
);
create index if not exists idx_notas_solic on public.notas(solicitacao_id);

-- ------------------------------------------------------------
-- TABELA: log  (auditoria)
-- ------------------------------------------------------------
create table if not exists public.log (
  id          bigint generated by default as identity primary key,
  user_id     uuid,
  acao        text,
  entidade    text,
  entidade_id uuid,
  created_at  timestamptz not null default now()
);

-- ============================================================
--  FUNÇÕES AUXILIARES
-- ============================================================

-- is_analista(): true se o usuário logado tem papel 'analista'.
-- SECURITY DEFINER + search_path fixo evita recursão de RLS.
create or replace function public.is_analista()
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'analista'
  );
$$;

-- handle_new_user(): cria o profile automaticamente quando um
-- usuário se cadastra (default papel 'cliente').
create or replace function public.handle_new_user()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- touch_updated_at(): mantém solicitacoes.updated_at em dia.
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_solic_touch on public.solicitacoes;
create trigger trg_solic_touch
  before update on public.solicitacoes
  for each row execute function public.touch_updated_at();

-- log_solicitacao(): registra mudanças de status na tabela log.
create or replace function public.log_solicitacao()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if (tg_op = 'INSERT') then
    insert into public.log(user_id, acao, entidade, entidade_id)
    values (auth.uid(), 'criou_solicitacao', 'solicitacoes', new.id);
  elsif (tg_op = 'UPDATE' and new.status is distinct from old.status) then
    insert into public.log(user_id, acao, entidade, entidade_id)
    values (auth.uid(), 'status:'||new.status::text, 'solicitacoes', new.id);
  end if;
  return new;
end;
$$;

drop trigger if exists trg_solic_log on public.solicitacoes;
create trigger trg_solic_log
  after insert or update on public.solicitacoes
  for each row execute function public.log_solicitacao();

-- ============================================================
--  ROW LEVEL SECURITY
-- ============================================================
alter table public.profiles     enable row level security;
alter table public.clientes      enable row level security;
alter table public.tomadores     enable row level security;
alter table public.solicitacoes  enable row level security;
alter table public.notas         enable row level security;
alter table public.log           enable row level security;

-- ---- profiles ----
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select
  using ( id = auth.uid() or public.is_analista() );

drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles for update
  using ( id = auth.uid() ) with check ( id = auth.uid() );

-- ---- clientes ----
drop policy if exists clientes_rw on public.clientes;
create policy clientes_rw on public.clientes for all
  using ( public.is_analista() or user_id = auth.uid() )
  with check ( public.is_analista() or user_id = auth.uid() );

-- ---- tomadores ----
drop policy if exists tomadores_rw on public.tomadores;
create policy tomadores_rw on public.tomadores for all
  using (
    public.is_analista()
    or cliente_id in (select id from public.clientes where user_id = auth.uid())
  )
  with check (
    public.is_analista()
    or cliente_id in (select id from public.clientes where user_id = auth.uid())
  );

-- ---- solicitacoes ----
drop policy if exists solic_rw on public.solicitacoes;
create policy solic_rw on public.solicitacoes for all
  using (
    public.is_analista()
    or cliente_id in (select id from public.clientes where user_id = auth.uid())
  )
  with check (
    public.is_analista()
    or cliente_id in (select id from public.clientes where user_id = auth.uid())
  );

-- ---- notas ----
-- Leitura: dono da solicitação ou analista. Escrita: somente analista.
drop policy if exists notas_select on public.notas;
create policy notas_select on public.notas for select
  using (
    public.is_analista()
    or solicitacao_id in (
      select s.id from public.solicitacoes s
      join public.clientes c on c.id = s.cliente_id
      where c.user_id = auth.uid()
    )
  );

drop policy if exists notas_write on public.notas;
create policy notas_write on public.notas for all
  using ( public.is_analista() )
  with check ( public.is_analista() );

-- ---- log ----
-- Auditoria visível somente para analistas. Inserção via triggers (definer).
drop policy if exists log_select on public.log;
create policy log_select on public.log for select
  using ( public.is_analista() );

-- ============================================================
--  STORAGE — bucket privado 'notas'
-- ============================================================
insert into storage.buckets (id, name, public)
values ('notas','notas', false)
on conflict (id) do nothing;

-- Convenção de caminho: notas/<cliente_id>/<solicitacao_id>/<arquivo>
-- Analista: acesso total. Cliente: lê apenas a própria pasta (1º segmento = cliente_id).

drop policy if exists notas_obj_analista on storage.objects;
create policy notas_obj_analista on storage.objects for all
  to authenticated
  using ( bucket_id = 'notas' and public.is_analista() )
  with check ( bucket_id = 'notas' and public.is_analista() );

drop policy if exists notas_obj_cliente_read on storage.objects;
create policy notas_obj_cliente_read on storage.objects for select
  to authenticated
  using (
    bucket_id = 'notas'
    and (storage.foldername(name))[1] in (
      select id::text from public.clientes where user_id = auth.uid()
    )
  );

-- ============================================================
--  FIM
-- ============================================================
